### ISSUE TITLE
Archives GitBook - May 2024

### ISSUE THREAD

**Issue by VanCardui** [SingularityNET-Archive/SingularityNET-Archive#126]

**Comment by VanCardui** [comment]
### Meeting summaries outstanding as of 31st May:

**Comment by EseWilliams** [comment]
Thursday 2nd of May

- [ ] Deep Funding Town Hall

Tuesday 7th of May
- [ ] Treasury Guild Operations ( No meeting summary )
- [ ] Governance Workgroup
- [ ] Ambassador Townhall

Wednesday 8th of May
- [ ] Education WG

Thursday 9th of May
- [ ] Deep Funding Townhall

Tuesday 14th of May
- [ ] Treasury Guild Operations ( No meeting summary )
- [ ] Governance Workgroup
- [ ] Ambassador Townhall

Thursday 16th of May
- [ ] Onboarding Workgroup

Friday 17th of May
- [ ] Writers Workgroup

Monday 20th of May
- [ ] Strategy Guild

Tuesday 21st of May
- [ ] Treasury Guild Operations ( No meeting summary )
- [ ] Governance Workgroup
- [ ] Ambassador Townhall
- [ ] Global Ethics initiative - Open Office

Wednesday 22nd of May
- [ ] Education Workgroup

Thursday 23rd of May
- [ ] Onboarding Workgroup

Friday 24th of May
- [ ] Writers Workgroup

Monday 27th of May
- [ ] Spotlight Day #1 - Deep Funding Proposal Pitch Event ( One-off event )
- [ ] Strategy guild

Tuesday 28th of May
- [ ] Treasury Guild Operations ( No meeting summary )
- [ ] Governance Workgroup
- [ ] Ambassador Townhall
- [ ] Latam Ambassador Townhall

Wednesday 29th of May
- [ ] Knowledge Base WG
- [ ] Archive Workgroup
- [ ] Education workgroup
- [ ] Spotlight Day #2 - Deep Funding Proposal Pitch Event ( One-off event)

Thursday 30th of May
- [ ] Onboarding Workgroup
- [ ] Spotlight Day #3 - Deep Funding Proposal Pitch Event ( One-off event)

Friday 31st of May
- [ ] Marketing guild session
- [ ] Writers Workgroup
- [ ] Video Workgroup
