### ISSUE TITLE
Set-up SingularityNET-Archive GitBook

### ISSUE THREAD

**Issue by stephen-rowan** [SingularityNET-Archive/SingularityNET-Archive#4]
- [x] Enable Lens - GitBook’s AI-powered search lets users ask questions in natural language and get answers based on your content. Enabling this setting only applies to content within this published space. [Learn more](https://docs.gitbook.com//product-tour/searching-your-content/lens).
- [x] [Get feedback / approval for nascent archive workgroup](https://github.com/SingularityNET-Archive/SingularityNET-Archive/issues/4#issuecomment-1509359354) - In Progress
- [x] [Migrate GitBook to SingularityNET GitBook account](https://github.com/SingularityNET-Archive/SingularityNET-Archive/issues/4#issuecomment-1509357729) - In Progress
- [x] [Onboard Ambassadors to GitBook usage](https://github.com/SingularityNET-Archive/SingularityNET-Archive/issues/4#issuecomment-1509365741) - In Progress
- [x] [Contributions to main](https://github.com/SingularityNET-Archive/SingularityNET-Archive/issues/4#issuecomment-1509392936) - audit trail - In Progress

**Comment by stephen-rowan** [comment]
## Migrate GitBook to SingularityNET GitBook account.

Peter added Stephen (@stephen-rowan) to the GitBook space but there seems to be an issue with minimum account members.

**Comment by stephen-rowan** [comment]
## Get feedback / approval for nascent archive workgroup

This has been raised in principle at SingularityNET Treasury Guild, Incubation and Process Guild meetings (Since beginning April 2023).

**Comment by stephen-rowan** [comment]
## SingularityNET Deep funding GitBook

- [ ] Locked out of this GitBook. Looks like a minimum free account restriction.

![Image](https://user-images.githubusercontent.com/25156451/232166290-e187e54e-d36a-43c8-96a4-4fba66395297.png)

**Comment by stephen-rowan** [comment]
## Onboard Ambassadors to GitBook useage

- [ ] Prepare short presentation on best practice use of GitBook
- [ ] Design and document workflow for archiving and updating content on SingularityNET GitBooks.

**Comment by stephen-rowan** [comment]
## SingularityNET Deep funding GitBook

- [ ] Would need admin access to setup backup connect to GitHub repository. I have editor only access which means I can only submit change requests.

**Comment by stephen-rowan** [comment]
## Contributions to main

### Apr 2, 2023 – Apr 15, 2023

![Image](https://user-images.githubusercontent.com/25156451/232170723-442c0443-4977-4c3b-871d-1228c85c3ee4.png)
